POST http://localhost:3500/api/user/register
Content-Type: application/json

{
    "name": "Linhhhhhh",
    "username": "linhh",
    "email": "linhlinhh@gmail.com",
    "password": "loverikka"
}

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "username": "datvn22",
    "password": "loverikka"
}
###
POST http://localhost:3000/api/user/logout
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWMzMmFiOThlODEyNDBmNzQxYzFmNTEiLCJ1c2VybmFtZSI6ImxpbmhoIiwiaWF0IjoxNjQwMTgxMzM4LCJleHAiOjE2NDAxODEzNTN9.qWorWdAs3BQQSFIQmw2HjGY2dyJqsjwu5rmw76nXskM
###
POST http://localhost:3000/api/user/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWJlY2E0YTMxN2I3YTQxNTMzYjE3MjkiLCJ1c2VybmFtZSI6ImRhdHZuMjIiLCJpYXQiOjE2NDAyMjk0NTEsImV4cCI6MTY0MDIzMzA1MX0.vVptqs1jr1RQHqJts8iZkNxTzTkNOOdc9bQp2uOWd_8"
}
###
POST http://localhost:3000/api/createpost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWMzMmFiOThlODEyNDBmNzQxYzFmNTEiLCJ1c2VybmFtZSI6ImxpbmhoIiwiaWF0IjoxNjQwMTgwNTE5LCJleHAiOjE2NDAxODA1MzR9.pHzabZvbJu2Tjo9cUw5sIZnoLsuKhY5QF8WZgG7C9H8
Content-Type: application/json

{
    "title": "demo post",
    "status": "Private",
    "content": "Rikka is so so so so so so so so so so so cute!"
}
###
GET http://localhost:3000/api/getposts
###
GET http://localhost:3000/api/linhh/getposts
###
GET http://localhost:3000/api/linhh/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWJlY2E0YTMxN2I3YTQxNTMzYjE3MjkiLCJ1c2VybmFtZSI6ImRhdHZuMjIiLCJpYXQiOjE2NDAyMjk1NjcsImV4cCI6MTY0MDIyOTU4Mn0.62S-rk2sm4GMH_CDwvAvKdHA160eDloo7tK_7PftGBA
###
DELETE http://localhost:3000/api/deletepost/61beea5addc0b3f5f5782746
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWJlZWI1NGRkYzBiM2Y1ZjU3ODI3NWIiLCJ1c2VybmFtZSI6ImRhdHZuMjEiLCJpYXQiOjE2Mzk5MDIwNjcsImV4cCI6MTYzOTkwMjA4Mn0.b4sm2YQcgFh8Z_Q8d4VJ7BdMbPH4iB55nhMPHtFv5q8
###
PATCH http://localhost:3000/api/updatepost/61beea5addc0b3f5f5782746
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWJlY2E0YTMxN2I3YTQxNTMzYjE3MjkiLCJ1c2VybmFtZSI6ImRhdHZuMjIiLCJpYXQiOjE2NDAxODc1NTEsImV4cCI6MTY0MDE4NzU2Nn0.i-kMrxzKS41UKJAreCNpC21R35u_0j_5h9oR0paW2dQ
Content-Type: application/json

{
    "title": "rikka post",
    "status": "Public",
    "content": "Rikka is so so so so so so so so so so so cute!"
}